#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

docker run -it \
  --name=developing-in-ros \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --rm \
  developing-in-ros "$@"