#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
  --name=${PROJECT_NAME} \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --volume ${PROJECT_ROOT}/../_ROSBase/python3_ws:/python3_ws \
  --rm \
  --runtime nvidia \
  --network host \
  ${PROJECT_NAME}