#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

docker run -it \
  -p 8899:8888 \
  --hostname=jetsonbot.local  \
  --rm \
  jupyterlab

# --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \

# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
