#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

echo "Building Docker image..."
docker build -t ros-manual-operation ${PROJECT_ROOT}

echo "Running catkin_make..."
${PROJECT_ROOT}/script/run "$@"