#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

docker run -it \
  --name=ros-manual-operation \
  --device=/dev/input/js0 \
  --device=/dev/i2c-1 \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --rm \
  ros-manual-operation "$@"
# ros-manual-operation sh ./autostart.sh
# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
