ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
BOARD_TAG = nano328
ARDUINO_LIBS = Wire
# USER_LIB_PATH = /home/pi/arduinoLibraries
# ARDUINO_LIBS = /zumo /Wire

include /usr/share/arduino/Arduino.mk
