#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

docker run -it \
  --name=arduino_builder \
  --device=/dev/ttyUSB0 \
  --volume ${PROJECT_ROOT}/src:/arduino \
  --rm \
  ros-video_streamming "$@"

# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
